name: syncmyschedule
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  flutter_vector_icons: ^2.0.0
  provider: ^6.1.5
  flutter_hooks: ^0.21.2
  flutter_svg: ^2.2.0
  google_fonts: ^6.3.0
  font_awesome_flutter: ^10.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png